config/routes.rb
Giveity::Application.routes.draw do
  match '/' => 'users#index'

  resources :donations

  resources :organizations do
    resources :donations
  end

  resources :users do
    resources :donations
  end

  match 'users/:id/compare' => 'users#compare'

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :money, :organization_id, :time, :user_id

  belongs_to :organization
  belongs_to :user
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all unless (params[:user_id] or params[:organization_id])
    @donations = Donation.where(:user_id => params[:user_id]) if params[:user_id]
    @donations = Donation.where(:organization_id => params[:organization_id]) if params[:organization_id]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new
    @donation.user_id = params[:user_id] if params[:user_id]
    @donation.organization_id = params[:organization_id] if params[:organization_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, :notice => 'Donation was successfully created.' }
        format.json { render :json => @donation, :status => :created, :location => @donation }
      else
        format.html { render :action => "new" }
        format.json { render :json => @donation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, :notice => 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @donation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :money %><br />
    <%= f.number_field :money %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :organization_id %><br />
    <%= f.number_field :organization_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table>
  <tr>
    <th>Time</th>
    <th>Money</th>
    <th>User</th>
    <th>Organization</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donations.each do |donation| %>
  <tr>
    <td><%= donation.time %></td>
    <td><%= donation.money %></td>
    <td><%= donation.user_id %></td>
    <td><%= donation.organization_id %></td>
    <td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Donation', new_donation_path %>
<%= link_to 'User Dashboard', users_path %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>
<%= link_to 'User dashboard', users_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time:</b>
  <%= @donation.time %>
</p>

<p>
  <b>Money:</b>
  <%= @donation.money %>
</p>

<p>
  <b>User:</b>
  <%= @donation.user_id %>
</p>

<p>
  <b>Organization:</b>
  <%= @donation.organization_id %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>